version: "3"
services:
  react-app:
    image: react
    stdin_open: true
    ports: 
      - "3000:3000"
    networks:
      - mern-app
  api-server:
    image: server6
    ports:
      - "5000:5000"
    networks:
      - mern-app
    depends_on:
      - mongo
    volumes:
      - mongo-data:/data/db
  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
